### ISSUE TITLE
Failed to activate the glist package

### ISSUE THREAD

**Issue by tessus** [jcouyang/glist#11]
[Enter steps to reproduce below:]

1. Install glist

**Atom Version**: 1.0.0
**System**: Mac OS X 10.9.5
**Thrown From**: [glist](https://github.com/jcouyang/glist) package, v1.0.11

### Stack Trace

Failed to activate the glist package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/helmutt/.atom/packages/glist/lib/glist-view.coffee:1:1)
  at /Users/helmutt/.atom/packages/glist/lib/glist-view.coffee:34:3
  at Object.<anonymous> (/Users/helmutt/.atom/packages/glist/lib/glist-view.coffee:434:5)
  at Object.<anonymous> (/Users/helmutt/.atom/packages/glist/lib/glist-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/helmutt/.atom/packages/glist/lib/glist.coffee:2:13)
  at Object.<anonymous> (/Users/helmutt/.atom/packages/glist/lib/glist.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:709:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:257:12)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:236:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:772:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:222:20)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:156:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -0:00.6.0 glist:toggle (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics"
    ]
  },
  "glist": {
    "userName": "tessus"
  }
}
```

### Installed Packages

```coffee
# User
glist, v1.0.11

# Dev
No dev packages
```

**Comment by stefankolb** [comment]
I'm experiencing the exact same issue.

Atom Version: 1.0.0
System: Mac OS X 10.10.4

**Comment by serapath** [comment]
same here

**Comment by Zacharias** [comment]
Same in Windows 7 x64 & Atom 1.0.2

**Comment by spikeheap** [comment]
This issue is also present on OSX 10.11 GM, Atom 1.0.15

**Comment by jcouyang** [comment]
this is due to glist is still using the old atom API, hopefully if i have time recently will update this or next month

**Comment by jcouyang** [comment]
I rewrote the whole package now it's version 2.0
please do upgrade and really appreciate any feedback

**Comment by tessus** [comment]
@jcouyang I've stopped using Atom altogether.

**Comment by piccolbo** [comment]
Problems solved for me

**Comment by stefankolb** [comment]
Great, problem solved, package is now working again. Thx :)

**Comment by brettz9** [comment]
I'm getting this problem despite being on 2.2.0. I also see that the token path is listed as C:\Users\brett\.atom\packages/glist/.config.cson and there is no `.config.cson` file there.

My only config now:
```cson
  glist:
    githubToken: "**********"
```
