### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by vikfroberg** [jcouyang/glist#12]
After installing the package

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.3
**Thrown From**: [glist](https://github.com/jcouyang/glist) package, v1.0.11

### Stack Trace

Uncaught TypeError: Cannot read property 'prototype' of undefined

```
At /Users/vikfroberg/.atom/packages/glist/lib/glist-view.coffee:4

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/vikfroberg/.atom/packages/glist/lib/glist-view.coffee:1:1)
  at /Users/vikfroberg/.atom/packages/glist/lib/glist-view.coffee:34:3
  at Object.<anonymous> (/Users/vikfroberg/.atom/packages/glist/lib/glist-view.coffee:434:5)
  at Object.<anonymous> (/Users/vikfroberg/.atom/packages/glist/lib/glist-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Volumes/Macbook Air/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/vikfroberg/.atom/packages/glist/lib/glist.coffee:2:13)
  at Object.<anonymous> (/Users/vikfroberg/.atom/packages/glist/lib/glist.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Volumes/Macbook Air/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Volumes/Macbook Air/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:709:34)
  at Package.module.exports.Package.activateConfig (/Volumes/Macbook Air/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:257:12)
  at PackageDetailView.module.exports.PackageDetailView.activate (/Volumes/Macbook Air/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:162:26)
  at PackageDetailView.module.exports.PackageDetailView.updateInstalledState (/Volumes/Macbook Air/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:200:12)
  at /Volumes/Macbook Air/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:234:24
  at Emitter.module.exports.Emitter.emit (/Volumes/Macbook Air/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/Volumes/Macbook Air/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:579:27)
  at /Volumes/Macbook Air/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:376:26
  at exit (/Volumes/Macbook Air/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:59:16)
  at triggerExitCallback (/Volumes/Macbook Air/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/Volumes/Macbook Air/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
     -2:56.5.0 core:select-left (atom-text-editor.editor.is-focused)
     -2:54.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:53.9.0 core:undo (atom-text-editor.editor.is-focused)
     -2:53.3.0 core:move-right (atom-text-editor.editor.is-focused)
     -2:53 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -2:51.4.0 core:save (atom-text-editor.editor.is-focused)
     -2:35.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:34.2.0 core:save (atom-text-editor.editor.is-focused)
     -2:23.6.0 core:select-all (atom-text-editor.editor.is-focused)
     -2:23.3.0 core:copy (atom-text-editor.editor.is-focused)
     -1:18.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  7x -1:15.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:03.9.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:03.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:03.1.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:59.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "atom-light-syntax"
    ],
    "disabledPackages": [
      "linter-eslint",
      "linter",
      "bracket-matcher"
    ],
    "ignoredNames": [
      ".git",
      ".DS_Store",
      "node_modules"
    ]
  }
}
```

### Installed Packages

```coffee
# User
language-babel, v0.10.2
markdown-lists, v0.0.2

# Dev
No dev packages
```

**Comment by j-walker23** [comment]
Hi all, did anyone ever figure this out? Seems to still be doing it with latest of all versions.

**Comment by wonderbeyond** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0-beta.0
**System**: Ubuntu 12.04.5
**Thrown From**: [glist](https://github.com/jcouyang/glist) package, v1.0.11


### Stack Trace

Uncaught TypeError: Cannot read property 'prototype' of undefined

```
At /home/wonder/.atom/packages/glist/lib/glist-view.coffee:1

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/home/wonder/.atom/packages/glist/lib/glist-view.coffee:1:1)
  at /home/wonder/.atom/packages/glist/lib/glist-view.coffee:34:3
  at Object.<anonymous> (/home/wonder/.atom/packages/glist/lib/glist-view.coffee:434:5)
  at Object.<anonymous> (/home/wonder/.atom/packages/glist/lib/glist-view.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/home/wonder/.atom/packages/glist/lib/glist.coffee:2:13)
  at Object.<anonymous> (/home/wonder/.atom/packages/glist/lib/glist.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:761:34)
  at Package.module.exports.Package.activateConfig (/usr/share/atom/resources/app.asar/src/package.js:263:14)
  at PackageDetailView.module.exports.PackageDetailView.activateConfig (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:212:26)
  at PackageDetailView.module.exports.PackageDetailView.completeInitialzation (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:156:12)
  at PackageDetailView.module.exports.PackageDetailView.loadPackage (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:168:21)
  at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:298:17
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:588:27)
  at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:379:26
  at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:60:16)
  at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
  at /usr/share/atom/resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:467:12)

```

### Commands

```
     -6:30 command-palette:toggle (atom-text-editor.editor.is-focused)
     -6:25.4.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -6:25.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -6:24.6.0 settings-view:open (atom-text-editor.editor.is-focused)
  2x -6:19.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      ".~*",
      "*.pyc"
    ],
    "projectHome": "/home/wonder/",
    "disabledPackages": [
      "linter-pylint",
      "clipboard-history",
      "auto-detect-indentation",
      "gulp-helper",
      "symbol-gen"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-django, v0.3.0
emmet-simplified, v2.5.0
image-view, v0.55.0
japanese-wrap, v0.2.7
jquery-snippets, v11.0.0
language-html-swig, v2.0.1
language-nginx, v0.6.0
linter, v1.6.0
project-manager, v2.6.1

# Dev
No dev packages
```

**Comment by jcouyang** [comment]
I rewrote the whole package now it's version 2.0
please do upgrade and really appreciate any feedback
