### ISSUE TITLE
Uncaught TypeError: Cannot read property '2' of null

### ISSUE THREAD

**Issue by brettz9** [jcouyang/glist#14]
[Steps to reproduce:]

1. Use ctrl-c, ctrl-g to have a new gist started locally
2. Save the file manually
3. Try to use ctrl-x, ctrl-s to save to Github and get the error below:

**Atom Version**: 1.0.19
**System**: Microsoft Windows 10 Home
**Thrown From**: [glist](https://github.com/jcouyang/glist) package, v2.0.2

### Stack Trace

Uncaught TypeError: Cannot read property '2' of null

```
At /C:/Users/brett/.atom/packages/glist/lib/glist.coffee:94

TypeError: Cannot read property '2' of null
  at Object.module.exports.Glist.getMeta (C:\Users\brett\.atom\packages\glist\lib\glist.coffee:55:63)
  at Object.module.exports.Glist.saveGist (C:\Users\brett\.atom\packages\glist\lib\glist.coffee:75:57)
  at atom-workspace.subscriptions.add.atom.commands.add.glist:saveGist (C:\Users\brett\.atom\packages\glist\lib\glist.coffee:31:82)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\brett\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:245:29)
  at C:\Users\brett\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\brett\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\brett\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\brett\AppData\Local\atom\app-1.0.19\resources\app.asar\src\window-event-handler.js:184:20)

```

### Commands

```
     -0:56.8.0 glist:toggle (atom-text-editor.editor.is-focused)
  3x -0:49.8.0 editor:move-to-beginning-of-word (atom-text-editor.editor.mini.is-focused)
  3x -0:47.9.0 editor:move-to-end-of-word (atom-text-editor.editor.mini.is-focused)
     -0:47.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:44.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:43.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:35.3.0 core:cut (atom-text-editor.editor.is-focused)
     -0:35.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:29.6.0 core:close (atom-text-editor.editor.is-focused)
     -0:24.5.0 glist:toggle (atom-text-editor.editor.is-focused)
  3x -0:19.7.0 editor:move-to-beginning-of-word (atom-text-editor.editor.mini.is-focused)
  3x -0:17.8.0 editor:move-to-end-of-word (atom-text-editor.editor.mini.is-focused)
     -0:16.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -0:12.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:06.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:03.2.0 glist:saveGist (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "openEmptyEditorOnStart": false,
    "disabledPackages": [
      "save-session",
      "remember-session",
      "jslint",
      "selection-highlight"
    ],
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "customFileTypes": {
      "source.json": [
        "mdastrc",
        "htmlhintrc",
        "jsonschema",
        "metadata"
      ],
      "htaccess": [
        "htaccess-sample"
      ],
      "source": [
        "[object Object]"
      ]
    },
    "projectHome": "C:/wamp/www"
  },
  "glist": {
    "githubToken": ".........",
    "gistDir": "C:\\Users\\brett\\.atom\\packages\\glist\\gists"
  }
}
```

### Installed Packages

```coffee
# User
autohide-tree-view, v0.25.1
bottom-dock, v0.3.5
copy-path, v0.1.1
es-identifier-highlight, v0.2.7
git-hide, v0.1.2
git-history, v3.1.0
glist, v2.0.2
language-diff, v0.3.1
language-gitignore, v0.2.0
language-htaccess, v0.1.1
linter, v1.9.1
linter-csslint, v1.1.0
linter-eslint, v3.1.1
linter-htmlhint, v0.2.0
linter-jsonlint, v1.0.1
linter-manager, v0.2.4
linter-markdown, v1.2.1
linter-package-json-validator, v0.2.2
linter-xmllint, v0.0.7
remember-file-positions, v0.1.6
symbols-tree-view, v0.10.1
todo-manager, v0.2.5
tree-view-git-branch, v0.0.6

# Dev
No dev packages
```

**Comment by jcouyang** [comment]
OMG, atom post all config include token here, ...I'll change a place for storing token somewhere for 
security

ps the issue should be because the directory in windows machine difference from unix... :( windows

**Comment by brettz9** [comment]
Ok, thanks, I've deleted the token to be safe anyways. Is the directory something I could change/test?

**Comment by jcouyang** [comment]
It's a regex that matching the path, I'll let you know when I have a proper solution, maybe changing to atom.Directory api instead

**Comment by jcouyang** [comment]
Hi, can you test on windows if version 2.0.4 fix the problem?
https://github.com/jcouyang/glist/commit/442ad41f8cdc47841b7baedf1c877dd85986dbb9

**Comment by brettz9** [comment]
Still getting an error:
```
/C:/Users/brett/.atom/packages/glist/lib/glist.coffee:94
Hide Stack Trace
TypeError: Cannot read property '2' of null
  at Object.module.exports.Glist.getMeta (C:\Users\brett\.atom\packages\glist\lib\glist.coffee:55:63)
  at Object.module.exports.Glist.saveGist (C:\Users\brett\.atom\packages\glist\lib\glist.coffee:75:57)
  at atom-workspace.subscriptions.add.atom.commands.add.glist:saveGist (C:\Users\brett\.atom\packages\glist\lib\glist.coffee:31:82)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\brett\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:245:29)
  at C:\Users\brett\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\brett\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\brett\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (C:\Users\brett\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\brett\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:245:29)
  at C:\Users\brett\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\brett\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\brett\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\brett\AppData\Local\atom\app-1.0.19\resources\app.asar\src\window-event-handler.js:184:20)
```

**Comment by jcouyang** [comment]
Did you update the package? 
In version 2.0.4 line 55 is in toggle method
https://github.com/jcouyang/glist/blob/master/lib/glist.coffee#L55

**Comment by brettz9** [comment]
Sorry for the delayed reply--it showed as though it had updated, but it apparently had not. Maybe a restart was needed or something, but now it is working, thanks!
